In [2]:
import pandas as pd

from data_preprocessingagent import DataPreprocessingAgent
from health_monitoring_agent import HealthMonitoringAgent

In [4]:
pre_agent=DataPreprocessingAgent()
train,test,rul=pre_agent.preprocess(
    "train_FD003.txt",
    "test_FD003.txt",
    "RUL_FD003.txt"
)
health_agent=HealthMonitoringAgent()
health_df=health_agent.monitor(train)
health_df.head()

Shape: (24720, 26)
Missing: 0
Duplicates: 0

,engine_id,cycle,setting1,setting2,sensor2,sensor3,sensor4,sensor6,sensor7,sensor8,...,sensor15_anomaly,sensor17_anomaly,sensor20_anomaly,sensor21_anomaly,Anomaly_Count,RUL_Health,Anomaly_Health,Health_Score,Health_Status,Alert
0,1,1,0.470930,0.769231,0.355972,0.370523,0.308580,1.0,0.208812,0.623529,...,0,0,0,0,0,100.0,100.0,100.000000,Healthy,Normal operation
1,1,2,0.546512,0.230769,0.388759,0.399100,0.309360,1.0,0.236590,0.647059,...,0,0,0,0,0,100.0,100.0,97.655816,Healthy,Normal operation
2,1,3,0.418605,0.307692,0.313817,0.353298,0.445398,1.0,0.230843,0.664706,...,0,0,0,0,0,100.0,100.0,97.013170,Healthy,Normal operation
3,1,4,0.383721,0.538462,0.487119,0.417107,0.237285,1.0,0.268199,0.647059,...,0,0,0,0,0,100.0,100.0,96.452752,Healthy,Normal operation
4,1,5,0.593023,0.461538,0.196721,0.476218,0.321217,1.0,0.245690,0.670588,...,0,0,0,0,0,100.0,100.0,96.035272,Healthy,Normal operation

### Available columns

In [5]:
print(health_df.columns.tolist())

['engine_id', 'cycle', 'setting1', 'setting2', 'sensor2', 'sensor3', 'sensor4', 'sensor6', 'sensor7', 'sensor8', 'sensor9', 'sensor10', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21', 'RUL', 'sensor2_trend', 'sensor3_trend', 'sensor4_trend', 'sensor6_trend', 'sensor7_trend', 'sensor8_trend', 'sensor9_trend', 'sensor10_trend', 'sensor11_trend', 'sensor12_trend', 'sensor13_trend', 'sensor14_trend', 'sensor15_trend', 'sensor17_trend', 'sensor20_trend', 'sensor21_trend', 'Degradation_Score', 'Degradation_Health', 'sensor2_anomaly', 'sensor3_anomaly', 'sensor4_anomaly', 'sensor6_anomaly', 'sensor7_anomaly', 'sensor8_anomaly', 'sensor9_anomaly', 'sensor10_anomaly', 'sensor11_anomaly', 'sensor12_anomaly', 'sensor13_anomaly', 'sensor14_anomaly', 'sensor15_anomaly', 'sensor17_anomaly', 'sensor20_anomaly', 'sensor21_anomaly', 'Anomaly_Count', 'RUL_Health', 'Anomaly_Health', 'Health_Score', 'Health_Status', 'Alert']

### fault detection dataframe

In [7]:
fault_df=health_df.copy()

In [8]:
def detect_fault(row):
    if row["Health_Status"]=="Critical":
        return "Fault Detected"
    elif row["Anomaly_Count"]>=3:
        return "Fault Detected"
    elif row["Degradation_Score"]>0.4:
        return "Fault Detected"
    else:
        return "Normal"

In [9]:
fault_df["Fault_Status"]=(
    fault_df.apply(
        detect_fault,
        axis=1
    )
)

### creating fault alerts

In [11]:
def create_alert(status):
    if status=="Fault Detected":
        return "Further analysis required"
    return "No Alert"

In [12]:
fault_df["Fault_Alert"]=(
    fault_df["Fault_Status"].apply(create_alert)
)

In [13]:
fault_df[
    [
        "engine_id",
        "cycle",
        "Health_Score",
        "Health_Status",
        "Anomaly_Count",
        "Fault_Status",
        "Fault_Alert"
    ]
].head(20)

,engine_id,cycle,Health_Score,Health_Status,Anomaly_Count,Fault_Status,Fault_Alert
0,1,1,100.000000,Healthy,0,Normal,No Alert
1,1,2,97.655816,Healthy,0,Normal,No Alert
2,1,3,97.013170,Healthy,0,Normal,No Alert
3,1,4,96.452752,Healthy,0,Normal,No Alert
4,1,5,96.035272,Healthy,0,Normal,No Alert
5,1,6,96.508289,Healthy,0,Normal,No Alert
6,1,7,96.836692,Healthy,0,Normal,No Alert
7,1,8,97.507475,Healthy,0,Normal,No Alert
8,1,9,96.096874,Healthy,0,Normal,No Alert
9,1,10,96.960142,Healthy,0,Normal,No Alert
10,1,11,97.817787,Healthy,0,Normal,No Alert
11,1,12,96.926206,Healthy,0,Normal,No Alert
12,1,13,96.889552,Healthy,0,Normal,No Alert
13,1,14,97.345022,Healthy,0,Normal,No Alert
14,1,15,97.863008,Healthy,0,Normal,No Alert
15,1,16,96.973138,Healthy,0,Normal,No Alert
16,1,17,95.254536,Healthy,0,Normal,No Alert
17,1,18,97.037528,Healthy,0,Normal,No Alert
18,1,19,97.403013,Healthy,0,Normal,No Alert
19,1,20,97.240054,Healthy,0,Normal,No Alert

In [14]:
fault_df["Fault_Status"].value_counts()

Fault_Status
Normal            23883
Fault Detected      837
Name: count, dtype: int64

In [15]:
fault_df.to_csv(
    "fault_detection_output.csv",
    index=False
)
print("Fault Detection Output Saved")

Fault Detection Output Saved

In [16]:
fault_df.columns.tolist()

['engine_id',
 'cycle',
 'setting1',
 'setting2',
 'sensor2',
 'sensor3',
 'sensor4',
 'sensor6',
 'sensor7',
 'sensor8',
 'sensor9',
 'sensor10',
 'sensor11',
 'sensor12',
 'sensor13',
 'sensor14',
 'sensor15',
 'sensor17',
 'sensor20',
 'sensor21',
 'RUL',
 'sensor2_trend',
 'sensor3_trend',
 'sensor4_trend',
 'sensor6_trend',
 'sensor7_trend',
 'sensor8_trend',
 'sensor9_trend',
 'sensor10_trend',
 'sensor11_trend',
 'sensor12_trend',
 'sensor13_trend',
 'sensor14_trend',
 'sensor15_trend',
 'sensor17_trend',
 'sensor20_trend',
 'sensor21_trend',
 'Degradation_Score',
 'Degradation_Health',
 'sensor2_anomaly',
 'sensor3_anomaly',
 'sensor4_anomaly',
 'sensor6_anomaly',
 'sensor7_anomaly',
 'sensor8_anomaly',
 'sensor9_anomaly',
 'sensor10_anomaly',
 'sensor11_anomaly',
 'sensor12_anomaly',
 'sensor13_anomaly',
 'sensor14_anomaly',
 'sensor15_anomaly',
 'sensor17_anomaly',
 'sensor20_anomaly',
 'sensor21_anomaly',
 'Anomaly_Count',
 'RUL_Health',
 'Anomaly_Health',
 'Health_Score',
 'Health_Status',
 'Alert',
 'Fault_Status',
 'Fault_Alert']